# Generated by Django 3.2.5 on 2021-07-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
    ]
